[versions]
agp = "8.12.3"
kotlin = "2.2.21"
ksp = "2.2.20-2.0.3"
cmake = "3.22.1"
aboutlibraries = "13.1.0"
activity = "1.11.0"
core = "1.17.0"
annotation = "1.9.1"
compose = "1.9.4"
composeMultiplatform = "1.9.3"
composeDestinations = "2.3.0"
navigation = "2.9.6"
coroutines = "1.10.2"
serialization = "1.9.0"
miuix = "0.7.1"
haze = "1.6.10"
mmkv = "1.3.14"
mmkv64 = "2.2.4"
koin = "4.1.1"
junit = "4.13.2"
timber = "5.0.1"
javet = "5.0.1"
okhttp = "5.3.0"
pangutext-android = "1.0.4"
lifecycle = "2.9.0"
commons-compress = "1.26.1"
runtime = "1.9.5"
material3 = "1.4.0"
coil = "3.0.4"
ktor = "2.3.8"
firebase = "34.6.0"
mlkitBarcode = "17.3.0"
cameraX = "1.4.2"

[libraries]
gradle-android = { module = "com.android.tools.build:gradle", version.ref = "agp" }
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-compose = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "composeMultiplatform" }
gradle-ksp = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core" }
androidx-annotation-jvm = { module = "androidx.annotation:annotation-jvm", version.ref = "annotation" }
camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraX" }
camera2Lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraX" }
camera2View = { module = "androidx.camera:camera-view", version.ref = "cameraX" }
cameraCore = { module = "androidx.camera:camera-core", version.ref = "cameraX" }
cameraVideo = { module = "androidx.camera:camera-video", version.ref = "cameraX" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-ui-unit = { module = "androidx.compose.ui:ui-unit", version.ref = "compose" }
compose-destinations-core = { module = "io.github.raamcosta.compose-destinations:core", version.ref = "composeDestinations" }
compose-destinations-ksp = { module = "io.github.raamcosta.compose-destinations:ksp", version.ref = "composeDestinations" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
miuix-core = { module = "top.yukonga.miuix.kmp:miuix", version.ref = "miuix" }
miuix-android = { module = "top.yukonga.miuix.kmp:miuix-android", version.ref = "miuix" }
haze-materials = { module = "dev.chrisbanes.haze:haze-materials", version.ref = "haze" }
mmkv = { module = "com.tencent:mmkv", version.ref = "mmkv" }
mmkv64 = { module = "com.tencent:mmkv", version.ref = "mmkv64" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
javet = { module = "com.caoccao.javet:javet-node-android", version.ref = "javet" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { module = "junit:junit", version.ref = "junit" }
pangutext-android = { module = "com.highcapable.pangutext:pangutext-android", version.ref = "pangutext-android" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "commons-compress" }
androidx-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "runtime" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }
coil-svg = { module = "io.coil-kt.coil3:coil-svg", version.ref = "coil" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
aboutlibraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "aboutlibraries" }
aboutlibraries-compose = { module = "com.mikepenz:aboutlibraries-compose", version.ref = "aboutlibraries" }
aboutlibraries-compose-m3 = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutlibraries" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase" }
firebase-crashlytics-ndk = { module = "com.google.firebase:firebase-crashlytics-ndk" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
mlkit-barcode-scanning = { module = "com.google.mlkit:barcode-scanning", version.ref = "mlkitBarcode" }

[bundles]
androidx = ["androidx-core-ktx", "androidx-activity-compose"]
compose-core = ["compose-runtime", "compose-foundation", "compose-ui"]
compose-tooling = ["compose-ui-tooling", "compose-ui-tooling-preview"]
compose-destinations = ["compose-destinations-core", "compose-destinations-ksp"]
kotlinx = ["kotlinx-coroutines-android", "kotlinx-serialization-json"]
miuix = ["miuix-core", "miuix-android"]
testing = ["junit", "kotlin-test", "kotlin-test-junit"]
ktor = ["ktor-client-core", "ktor-client-android", "ktor-client-content-negotiation", "ktor-serialization-kotlinx-json"]

[plugins]
gradleAndroid = { id = "com.android.tools.build:gradle", version.ref = "agp" }
gradleKotlin = { id = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradleCompose = { id = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "composeMultiplatform" }
gradleKsp = { id = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
aboutlibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutlibraries" }
